language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache

global:
  - secure: "nTXMNU2aYbCtvKD74PndF8Xm2h6IvsxPjr6vj45AxjXmaB7Wf5oGi/4b6ObV\nexBtUQkFnc+M0ThGyUznOCPi3YxcbTzsyhQYhHUtmtw/6QRyYgo4E0GLDItU\n37Ff6wpxl3NMMJTvpi6SOVUvIJUl3+cs+4bkMkS48RSFGg2rGmo="  # Coveralls.io token
matrix:
  fast_finish: true
  include:
      - python: "3.8"
        env: TOXENV=isort,lint
      - python: "3.7"
        env: TOXENV=docs
      - python: "2.7"
        env: TOXENV=py27-plone-5.2
      - python: "2.7"
        env: TOXENV=py27-plone-5.2-archetypes
      - python: "3.6"
        env: TOXENV=py36-plone-5.2
      - python: "3.7"
        env: TOXENV=py37-plone-5.2
      - python: "3.8"
        env: TOXENV=py38-plone-5.2

before_install:
    - mkdir -p $HOME/buildout-cache/{downloads,eggs,extends}
    - mkdir $HOME/.buildout
    - echo "[buildout]" > $HOME/.buildout/default.cfg
    - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
    - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
    - echo "extends-cache = $HOME/buildout-cache/extends" >> $HOME/.buildout/default.cfg
    - echo "abi-tag-eggs = true" >> $HOME/.buildout/default.cfg

install:
  - travis_retry pip install -U pip tox coveralls coverage

script:
    - travis_retry tox

after_success:
    - coverage combine
    - coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#sprint"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
