language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs

env:
- PLONE_VERSION=4.3
- PLONE_VERSION=5.0
global:
  - secure: "nTXMNU2aYbCtvKD74PndF8Xm2h6IvsxPjr6vj45AxjXmaB7Wf5oGi/4b6ObV\nexBtUQkFnc+M0ThGyUznOCPi3YxcbTzsyhQYhHUtmtw/6QRyYgo4E0GLDItU\n37Ff6wpxl3NMMJTvpi6SOVUvIJUl3+cs+4bkMkS48RSFGg2rGmo="  # Coveralls.io token
matrix:
  allow_failures:
  - env: PLONE_VERSION=4.0
  - env: PLONE_VERSION=4.1
  - env: PLONE_VERSION=5.0
  include:
    - python: 2.6
      env: PLONE_VERSION=4.0
    - python: 2.6
      env: PLONE_VERSION=4.1
    - python: 2.6
      env: PLONE_VERSION=4.2
  fast_finish: true

install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - sed -ie "s#-4.3.x#-$PLONE_VERSION.x#" buildout.cfg
  - make "bin/python"
  - bin/python bootstrap.py
  - bin/buildout annotate
  - make version=$TRAVIS_PYTHON_VERSION .installed.cfg

script:
  - bin/code-analysis
  - make coverage

after_success:
- pip install python-coveralls==2.4.0
- coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#sprint"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
