language: python
python:
  - 2.6
  - 2.7

env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3

matrix:
  allow_failures:
    - env: PLONE_VERSION=4.3

install:
  - sed -ie "s#test-4.2.x.cfg#test-$PLONE_VERSION.x.cfg#" buildout.cfg
  - make python=$( which python ) .installed.cfg

script:
  - make tests

notifications:
  irc:
    - "irc.freenode.org#sprint"
